"""add website to contacts

Revision ID: 3fb9b15cffbb
Revises: e54389bd9ec2
Create Date: 2026-07-27 18:21:02.765665

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fb9b15cffbb"
down_revision: str | None = "e54389bd9ec2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("website", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "website")
    # ### end Alembic commands ###
