"""initial schema

Revision ID: e54389bd9ec2
Revises:
Create Date: 2026-03-29 22:05:17.758026

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e54389bd9ec2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("reminder_frequency", sa.String(length=50), nullable=True),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_contacts_email", "contacts", ["email"], unique=False)
    op.create_index("idx_contacts_phone", "contacts", ["phone"], unique=False)
    op.create_index("idx_contacts_tenant", "contacts", ["tenant_id"], unique=False)
    op.create_index(
        "idx_contacts_tenant_created", "contacts", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("contact_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("interaction_type", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("raw_transcript", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_interactions_contact", "interactions", ["contact_id"], unique=False)
    op.create_index("idx_interactions_occurred", "interactions", ["occurred_at"], unique=False)
    op.create_index("idx_interactions_tenant", "interactions", ["tenant_id"], unique=False)
    op.create_index(
        "idx_interactions_tenant_created", "interactions", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("contact_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("tenant_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "CANCELLED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_due", "tasks", ["due_date"], unique=False)
    op.create_index("idx_tasks_reminder", "tasks", ["reminder_at", "reminder_sent"], unique=False)
    op.create_index("idx_tasks_tenant_status", "tasks", ["tenant_id", "status"], unique=False)
    op.create_table(
        "proposals",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_message_id", sa.String(length=255), nullable=True),
        sa.Column("whatsapp_user_id", sa.String(length=100), nullable=False),
        sa.Column("extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "EDITED", "REJECTED", name="proposalstatus"),
            nullable=False,
        ),
        sa.Column("contact_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("interaction_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_proposals_tenant_status", "proposals", ["tenant_id", "status"], unique=False
    )
    op.create_index("idx_proposals_user", "proposals", ["whatsapp_user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_proposals_user", table_name="proposals")
    op.drop_index("idx_proposals_tenant_status", table_name="proposals")
    op.drop_table("proposals")
    op.drop_index("idx_tasks_tenant_status", table_name="tasks")
    op.drop_index("idx_tasks_reminder", table_name="tasks")
    op.drop_index("idx_tasks_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_interactions_tenant_created", table_name="interactions")
    op.drop_index("idx_interactions_tenant", table_name="interactions")
    op.drop_index("idx_interactions_occurred", table_name="interactions")
    op.drop_index("idx_interactions_contact", table_name="interactions")
    op.drop_table("interactions")
    op.drop_index("idx_contacts_tenant_created", table_name="contacts")
    op.drop_index("idx_contacts_tenant", table_name="contacts")
    op.drop_index("idx_contacts_phone", table_name="contacts")
    op.drop_index("idx_contacts_email", table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
